namespace Eddy.x12.Models.v4020;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v4010.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
