namespace Eddy.x12.Models.v4020;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v4010.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
