namespace Eddy.x12.Models.v6010;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v5050.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
