namespace Eddy.x12.Models.v6010;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v5050.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
