namespace Eddy.x12.Models.v6010;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v5050.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
