namespace Eddy.x12.Models.v6010;

public class BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation : Eddy.x12.Models.v5050.BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation
{
}
