namespace Eddy.x12.Models.v7040;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v7030.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
