namespace Eddy.x12.Models.v7040;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v7030.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
