namespace Eddy.x12.Models.v7040;

public class BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation : Eddy.x12.Models.v7030.BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation
{
}
