namespace Eddy.x12.Models.v7050;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v7040.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
