namespace Eddy.x12.Models.v7050;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v7040.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
