namespace Eddy.x12.Models.v7050;

public class BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation : Eddy.x12.Models.v7040.BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation
{
}
