namespace Eddy.x12.Models.v7060;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v7050.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
