namespace Eddy.x12.Models.v7060;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v7050.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
