namespace Eddy.x12.Models.v7060;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v7050.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
