namespace Eddy.x12.Models.v7060;

public class BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation : Eddy.x12.Models.v7050.BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation
{
}
