namespace Eddy.x12.Models.v8040;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v8030.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
