namespace Eddy.x12.Models.v8040;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v8030.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
