namespace Eddy.x12.Models.v8040;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v8030.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
