namespace Eddy.x12.Models.v6040;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v6030.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
