namespace Eddy.x12.Models.v6040;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v6030.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
