namespace Eddy.x12.Models.v6040;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v6030.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
