namespace Eddy.x12.Models.v8020;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v8010.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
