namespace Eddy.x12.Models.v8020;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v8010.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
