namespace Eddy.x12.Models.v8020;

public class BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation : Eddy.x12.Models.v8010.BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation
{
}
