namespace Eddy.x12.Models.v6030;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v6020.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
