namespace Eddy.x12.Models.v6030;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v6020.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
