namespace Eddy.x12.Models.v6030;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v6020.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
