namespace Eddy.x12.Models.v6030;

public class BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation : Eddy.x12.Models.v6020.BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation
{
}
