namespace Eddy.x12.Models.v7030;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v7020.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
