namespace Eddy.x12.Models.v7030;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v7020.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
