namespace Eddy.x12.Models.v7030;

public class BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation : Eddy.x12.Models.v7020.BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation
{
}
