namespace Eddy.x12.Models.v7020;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v7010.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
