namespace Eddy.x12.Models.v7020;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v7010.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
