namespace Eddy.x12.Models.v7020;

public class BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation : Eddy.x12.Models.v7010.BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation
{
}
