namespace Eddy.x12.Models.v5030;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v5020.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
