namespace Eddy.x12.Models.v7010;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v6050.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
