namespace Eddy.x12.Models.v7010;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v6050.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
