namespace Eddy.x12.Models.v7010;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v6050.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
