namespace Eddy.x12.Models.v8030;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v8020.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
