namespace Eddy.x12.Models.v5040;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v5030.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
