namespace Eddy.x12.Models.v5040;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v5030.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
