namespace Eddy.x12.Models.v5040;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v5030.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
