namespace Eddy.x12.Models.v5010;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v4060.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
