namespace Eddy.x12.Models.v5010;

public class BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation : Eddy.x12.Models.v4060.BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation
{
}
