namespace Eddy.x12.Models.v8010;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v7060.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
