namespace Eddy.x12.Models.v8010;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v7060.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
