namespace Eddy.x12.Models.v8010;

public class BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation : Eddy.x12.Models.v7060.BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation
{
}
