namespace Eddy.x12.Models.v4060;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v4050.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
