namespace Eddy.x12.Models.v4060;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v4050.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
