namespace Eddy.x12.Models.v4050;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v4040.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
