namespace Eddy.x12.Models.v4050;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v4040.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
