namespace Eddy.x12.Models.v6020;

public class BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation : Eddy.x12.Models.v6010.BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation
{
}
