namespace Eddy.x12.Models.v5020;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v5010.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
