namespace Eddy.x12.Models.v5020;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v5010.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
