namespace Eddy.x12.Models.v4040;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v4030.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
