namespace Eddy.x12.Models.v4030;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v4020.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
