namespace Eddy.x12.Models.v6050;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v6040.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
