namespace Eddy.x12.Models.v6050;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v6040.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
