namespace Eddy.x12.Models.v6050;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v6040.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
