namespace Eddy.x12.Models.v6050;

public class BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation : Eddy.x12.Models.v6040.BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation
{
}
