using System.Reflection;
using Eddy.Core.Attributes;
using Eddy.Core.Metadata;

namespace Eddy.MetadataTool;

/// <summary>
/// Builds a metadata pack purely from what Eddy.Core.Metadata.DerivedSegmentMetadata can compute from the
/// model types themselves -- no data files. Backs the `derive` command (docs/metadata-packs.md, "Tool").
/// The result has no real standard data element numbers: positions with none get a synthetic
/// "&lt;SEG&gt;-&lt;pos&gt;" key, and the pack's provenance says so, so it is obviously a starting point to
/// inspect or hand-edit rather than a finished pack.
/// </summary>
public static class PackDeriver
{
    /// <summary>Derives a pack for <paramref name="standard"/> ("X12" or "EDIFACT") and
    /// <paramref name="version"/> (any shorthand <see cref="MetadataCatalog.NormalizeVersion"/> accepts).
    /// Throws <see cref="ArgumentException"/> for an unrecognised standard, and
    /// <see cref="InvalidOperationException"/> when no model types are found for the version.</summary>
    public static MetadataPackModel Derive(string standard, string version)
    {
        if (standard != "X12" && standard != "EDIFACT")
            throw new ArgumentException("standard must be X12 or EDIFACT", nameof(standard));

        var normalizedVersion = MetadataCatalog.NormalizeVersion(standard, version)
            ?? throw new ArgumentException($"could not normalise version '{version}' for {standard}", nameof(version));

        var types = ModelTypes(standard, normalizedVersion);
        if (types.Count == 0)
        {
            throw new InvalidOperationException(
                $"no {standard} model types found for version {version} (looked for namespace {NamespacePrefix(standard, normalizedVersion)}[.Composites])");
        }

        var pack = new MetadataPackModel
        {
            Standard = standard,
            Version = normalizedVersion,
            Name = $"{standard} {normalizedVersion} derived from Eddy models",
            Provenance =
                $"Generated by Eddy.MetadataTool derive from the Eddy.{(standard == "X12" ? "x12" : "Edifact")} " +
                $"model types for {normalizedVersion}. Segment/composite structure, coarse types (AN/N/R/DT/TM) " +
                "and requirement come from the models' [Position] attributes and Validate() probing " +
                "(Eddy.Core.Metadata.DerivedSegmentMetadata) -- there are no real standard data element numbers " +
                "here. Positions with no known number are keyed \"<SEG>-<pos>\" below; replace them by hand, or " +
                "with import-biztalk/import-codes, before relying on this pack for data element identity.",
        };

        foreach (var type in types)
            AddDerivedType(pack, type, standard, normalizedVersion);

        return pack;
    }

    private static string NamespacePrefix(string standard, string normalizedVersion) => standard == "X12"
        ? $"Eddy.x12.Models.v{normalizedVersion[2..]}"
        : $"Eddy.Edifact.Models.{normalizedVersion}";

    /// <summary>Every segment and composite type for one standard/version: a [Segment] attribute or an
    /// EdiX12Component/EdifactComponent base, declared directly in that version's namespace (or its
    /// .Composites sub-namespace) -- inherited members (a version that reuses an older one's composite
    /// unchanged) are still picked up, since GetProperties() includes them.</summary>
    private static List<Type> ModelTypes(string standard, string normalizedVersion)
    {
        var nsPrefix = NamespacePrefix(standard, normalizedVersion);
        var composites = nsPrefix + ".Composites";

        var assembly = standard == "X12"
            ? typeof(Eddy.x12.Models.EdiX12Segment).Assembly
            : typeof(Eddy.Edifact.EdifactSegment).Assembly;

        return assembly.GetTypes()
            .Where(t => t.IsClass && !t.IsAbstract && t.Namespace is not null && (t.Namespace == nsPrefix || t.Namespace == composites))
            .Where(t => t.GetCustomAttribute<Segment>(true) is not null || IsComponentType(standard, t))
            .OrderBy(t => t.Name, StringComparer.Ordinal)
            .ToList();
    }

    private static bool IsComponentType(string standard, Type type) => standard == "X12"
        ? typeof(Eddy.x12.Models.EdiX12Component).IsAssignableFrom(type)
        : typeof(Eddy.Edifact.EdifactComponent).IsAssignableFrom(type);

    private static void AddDerivedType(MetadataPackModel pack, Type type, string standard, string normalizedVersion)
    {
        var def = DerivedSegmentMetadata.Describe(type, standard, normalizedVersion);
        var component = new ComponentDef { Name = def.Name };

        foreach (var element in def.Elements)
        {
            ElementRef elementRef;
            if (element.DataType == ElementDataType.Composite)
            {
                // The composite's own type is enumerated separately (it lives in the same version's
                // namespace) and keyed by its own Id, so just reference it here.
                elementRef = new ElementRef { Pos = element.Position, Composite = element.CompositeId, Req = FormatRequirement(element.Requirement) };
            }
            else
            {
                var key = element.DataElementNumber ?? $"{def.Id}-{element.Position}";
                if (!pack.DataElements.ContainsKey(key))
                {
                    pack.DataElements[key] = new DataElementDef
                    {
                        Name = element.Name,
                        Type = FormatType(element.DataType, element.Decimals),
                        Min = element.MinLength,
                        Max = element.MaxLength,
                    };
                }
                elementRef = new ElementRef { Pos = element.Position, De = key, Req = FormatRequirement(element.Requirement) };
            }

            component.Elements.Add(elementRef);
        }

        if (IsComponentType(standard, type))
            pack.Composites[def.Id] = component;
        else
            pack.Segments[def.Id] = component;
    }

    private static string FormatType(ElementDataType type, int? decimals) => type switch
    {
        ElementDataType.Identifier => "ID",
        ElementDataType.AlphaNumeric => "AN",
        ElementDataType.Numeric => decimals is > 0 ? "N" + decimals : "N",
        ElementDataType.Decimal => "R",
        ElementDataType.Date => "DT",
        ElementDataType.Time => "TM",
        ElementDataType.Binary => "B",
        _ => "AN", // Unknown derived type: default to the least restrictive formal type rather than write an invalid one.
    };

    private static string? FormatRequirement(Requirement requirement) => requirement switch
    {
        Requirement.Mandatory => "M",
        Requirement.Optional => "O",
        Requirement.Conditional => "C",
        _ => null,
    };
}
