using System.Text.Json.Nodes;
using Eddy.MetadataTool;

if (args.Length == 0)
{
    PrintUsage();
    return 1;
}

var command = args[0];
var rest = args[1..];

try
{
    return command switch
    {
        "import-biztalk" => RunImportBiztalk(Args.Parse(rest)),
        "import-codes" => RunImportCodes(Args.Parse(rest)),
        "merge" => RunMerge(Args.Parse(rest)),
        "derive" => RunDerive(Args.Parse(rest)),
        "validate" => RunValidate(Args.Parse(rest)),
        "-h" or "--help" or "help" => Help(),
        _ => Unknown(command),
    };
}
catch (FormatException ex)
{
    Console.Error.WriteLine($"error: {ex.Message}");
    return 1;
}
catch (FileNotFoundException ex)
{
    Console.Error.WriteLine($"error: {ex.Message}");
    return 1;
}
catch (DirectoryNotFoundException ex)
{
    Console.Error.WriteLine($"error: {ex.Message}");
    return 1;
}

static int Help()
{
    PrintUsage();
    return 0;
}

static int Unknown(string command)
{
    Console.Error.WriteLine($"error: unknown command '{command}'");
    PrintUsage();
    return 1;
}

static void PrintUsage()
{
    Console.Error.WriteLine("""
        Eddy.MetadataTool - generates metadata packs for Eddy (docs/metadata-packs.md)

        Usage:
          import-biztalk --dir <folder> --version <D96A> --out <file> [--provenance <text>]
          import-codes   --standard X12|EDIFACT --version <v> --csv <file> --out <file>
          merge          <a.json> <b.json> ... --out <file>
          derive         --standard X12|EDIFACT --version <v> --out <file>
          validate       <file>
        """);
}

static int RunImportBiztalk(Args args)
{
    var dir = args.Require("dir");
    var version = args.Require("version");
    var outPath = args.Require("out");
    var provenanceOverride = args.Optional("provenance");

    if (!Directory.Exists(dir))
    {
        Console.Error.WriteLine($"error: directory not found: {dir}");
        return 1;
    }

    var files = Directory.GetFiles(dir, "EFACT_*.xsd").OrderBy(f => f, StringComparer.Ordinal).ToArray();
    if (files.Length == 0)
    {
        Console.Error.WriteLine($"error: no EFACT_*.xsd files found in {dir}");
        return 1;
    }

    var pack = new MetadataPackModel
    {
        Standard = "EDIFACT",
        Version = version,
        Name = $"EDIFACT {version} from BizTalk schemas",
        License = "MIT (Microsoft Corporation)",
        Provenance = provenanceOverride ??
            $"Generated by Eddy.MetadataTool import-biztalk from github.com/microsoft/Integration, " +
            $"path \"BizTalk Server/Schema/EDIFACT/{version}\"",
    };

    var dataElementSource = new Dictionary<string, string>(StringComparer.Ordinal);
    var compositeSource = new Dictionary<string, string>(StringComparer.Ordinal);
    var segmentSource = new Dictionary<string, string>(StringComparer.Ordinal);

    var warningCount = 0;
    foreach (var file in files)
    {
        var fileName = Path.GetFileName(file);
        BiztalkFileImport imported;
        try
        {
            imported = BiztalkXsdParser.Parse(file);
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"warning: {fileName}: could not parse ({ex.Message}); skipped");
            warningCount++;
            continue;
        }

        foreach (var w in imported.Warnings)
        {
            Console.Error.WriteLine($"warning: {fileName}: {w}");
            warningCount++;
        }

        foreach (var (key, def) in imported.DataElements)
        {
            if (!pack.DataElements.TryGetValue(key, out var existing))
            {
                pack.DataElements[key] = def;
                dataElementSource[key] = fileName;
            }
            else if (!existing.StructurallyEquals(def))
            {
                Console.Error.WriteLine(
                    $"warning: data element {key} disagrees between {dataElementSource[key]} " +
                    $"({existing.Type} {existing.Min}..{existing.Max}) and {fileName} ({def.Type} {def.Min}..{def.Max}); keeping the first");
                warningCount++;
            }
        }

        MergeComponents(pack.Composites, imported.Composites, compositeSource, fileName, "composite");
        MergeComponents(pack.Segments, imported.Segments, segmentSource, fileName, "segment");

        foreach (var (de, codes) in imported.Codes)
        {
            if (!pack.Codes.TryGetValue(de, out var map))
                pack.Codes[de] = map = new Dictionary<string, string>();
            foreach (var code in codes.Keys)
                map.TryAdd(code, "");
        }
    }

    PackJson.Save(pack, outPath);
    Console.WriteLine(
        $"Wrote {outPath}: {pack.Segments.Count} segments, {pack.Composites.Count} composites, " +
        $"{pack.DataElements.Count} data elements, {pack.Codes.Values.Sum(m => m.Count)} codes " +
        $"from {files.Length} schema files ({warningCount} warnings)");
    return 0;
}

static void MergeComponents(Dictionary<string, ComponentDef> target, Dictionary<string, ComponentDef> incoming, Dictionary<string, string> source, string fileName, string kind)
{
    foreach (var (key, def) in incoming)
    {
        if (!target.TryGetValue(key, out var existing))
        {
            target[key] = def;
            source[key] = fileName;
        }
        else if (!existing.StructurallyEquals(def))
        {
            Console.Error.WriteLine($"warning: {kind} {key} disagrees between {source[key]} and {fileName}; keeping the first definition");
        }
    }
}

static int RunImportCodes(Args args)
{
    var standard = args.Require("standard");
    var version = args.Require("version");
    var csv = args.Require("csv");
    var outPath = args.Require("out");

    if (standard != "X12" && standard != "EDIFACT")
    {
        Console.Error.WriteLine("error: --standard must be X12 or EDIFACT");
        return 1;
    }
    if (!File.Exists(csv))
    {
        Console.Error.WriteLine($"error: csv file not found: {csv}");
        return 1;
    }

    var csvName = Path.GetFileName(csv);
    var pack = new MetadataPackModel
    {
        Standard = standard,
        Version = version,
        Name = $"{standard} {version} codes from {csvName}",
        Provenance = $"Imported by Eddy.MetadataTool import-codes from {csvName}",
    };

    var rowCount = 0;
    foreach (var row in CsvCodes.Read(csv))
    {
        if (!pack.Codes.TryGetValue(row.DataElement, out var map))
            pack.Codes[row.DataElement] = map = new Dictionary<string, string>();
        map[row.Code] = row.Description;
        rowCount++;
    }

    PackJson.Save(pack, outPath);
    Console.WriteLine($"Wrote {outPath}: {pack.Codes.Count} code lists, {rowCount} codes from {csvName}");
    return 0;
}

static int RunMerge(Args args)
{
    var outPath = args.Require("out");
    var files = args.Positional;
    if (files.Count == 0)
    {
        Console.Error.WriteLine("error: merge requires at least one input file");
        return 1;
    }

    JsonObject? merged = null;
    string? standard = null;
    string? version = null;

    foreach (var file in files)
    {
        if (!File.Exists(file))
        {
            Console.Error.WriteLine($"error: file not found: {file}");
            return 1;
        }

        var node = JsonNode.Parse(File.ReadAllText(file)) ?? throw new FormatException($"{file}: empty JSON document");
        var root = (JsonObject)node;
        var fileStandard = (string?)root["standard"];
        var fileVersion = (string?)root["version"];

        if (standard is null)
        {
            standard = fileStandard;
            version = fileVersion;
        }
        else if (fileStandard != standard || fileVersion != version)
        {
            Console.Error.WriteLine(
                $"error: {file} has standard/version {fileStandard}/{fileVersion}, expected {standard}/{version} (from earlier input files)");
            return 1;
        }

        merged = merged is null ? root : PackMerge.DeepMerge(merged, root);
    }

    var pack = PackJson.Parse(merged!);
    PackJson.Save(pack, outPath);
    Console.WriteLine($"Wrote {outPath} merged from {files.Count} files");
    return 0;
}

static int RunDerive(Args args)
{
    var standard = args.Require("standard");
    var version = args.Require("version");
    var outPath = args.Require("out");

    MetadataPackModel pack;
    try
    {
        pack = PackDeriver.Derive(standard, version);
    }
    catch (ArgumentException ex)
    {
        Console.Error.WriteLine($"error: {ex.Message}");
        return 1;
    }
    catch (InvalidOperationException ex)
    {
        Console.Error.WriteLine($"error: {ex.Message}");
        return 1;
    }

    PackJson.Save(pack, outPath);
    Console.WriteLine(
        $"Wrote {outPath}: {pack.Segments.Count} segments, {pack.Composites.Count} composites, " +
        $"{pack.DataElements.Count} data elements derived from the Eddy model types");
    return 0;
}

static int RunValidate(Args args)
{
    if (args.Positional.Count != 1)
    {
        Console.Error.WriteLine("error: validate requires exactly one file argument");
        return 1;
    }

    var file = args.Positional[0];
    if (!File.Exists(file))
    {
        Console.Error.WriteLine($"error: file not found: {file}");
        return 1;
    }

    var pack = PackJson.Load(file);
    var result = PackValidator.Validate(pack);

    Console.WriteLine(
        $"{file}: {result.SegmentCount} segments, {result.CompositeCount} composites, " +
        $"{result.DataElementCount} data elements, {result.CodeListCount} code lists, {result.CodeCount} codes");

    if (result.IsValid)
    {
        Console.WriteLine("OK");
        return 0;
    }

    foreach (var problem in result.Problems)
        Console.Error.WriteLine($"error: {problem}");
    Console.Error.WriteLine($"{result.Problems.Count} problem(s) found");
    return 1;
}
