namespace Eddy.x12.Models.v5050;

public class BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID : Eddy.x12.Models.v5040.BAX_BeginningSegmentForAdvanceConsistAndTransportationAutomaticEquipmentID
{
}
