namespace Eddy.x12.Models.v5050;

public class BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity : Eddy.x12.Models.v5040.BJF_BeginningSegmentRailroadJunctionsAndInterchangesUpdateActivity
{
}
