namespace Eddy.x12.Models.v5050;

public class BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement : Eddy.x12.Models.v5040.BOS_BeginningSegmentForJointInterestBillingAndOperatingExpenseStatement
{
}
