namespace Eddy.x12.Models.v5050;

public class BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation : Eddy.x12.Models.v5040.BSC_BeginningSegmentForCommissionSalesReportAndPeriodicCompensation
{
}
