name: Publish Edifact.Transport NuGet Package

on:
  workflow_run:
    workflows: ["Publish Eddy.Edifact NuGet Package"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Read version
      id: version
      run: |
        version=$(cat version.txt)
        echo "version=$version" >> "$GITHUB_OUTPUT"

    - name: Add GitHub NuGet source
      run: |
        dotnet nuget add source \
        --username "${{ github.actor }}" \
        --password "${{ secrets.GITHUB_TOKEN }}" \
        --store-password-in-clear-text \
        --name github \
        "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Update Eddy.Core package
      run: |
        dotnet add Eddy.Edifact.DomainModels.Transport/Eddy.Edifact.DomainModels.Transport.csproj \
          package Eddy.Core --version ${{ steps.version.outputs.version }}-${{vars.GLOBAL_VERSION_SUFFIX}}

    - name: Restore dependencies
      run: dotnet restore Eddy.Edifact.DomainModels.Transport/Eddy.Edifact.DomainModels.Transport.csproj

    - name: Build
      run: dotnet build Eddy.Edifact.DomainModels.Transport/Eddy.Edifact.DomainModels.Transport.csproj --no-restore -c Release /p:Version=${{ steps.version.outputs.version }}

    - name: Pack
      run: |
        dotnet pack Eddy.Edifact.DomainModels.Transport/Eddy.Edifact.DomainModels.Transport.csproj \
        --no-build -c Release -o out \
        /p:PackageVersion=${{ steps.version.outputs.version }}-${{vars.GLOBAL_VERSION_SUFFIX}}

    - name: Push to NuGet.org
      run: |
        dotnet nuget push out/*.nupkg \
        --api-key ${{ secrets.NUGET_API_KEY }} \
        --source https://api.nuget.org/v3/index.json

    - name: Push to GitHub Packages
      run: |
        dotnet nuget push out/*.nupkg \
        --api-key ${{ secrets.GITHUB_TOKEN }} \
        --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
