name: Publish Eddy.Core NuGet Package

on:
  push:
    branches: [ main ]
    paths:
      - 'Eddy.Core/**'
      - '.github/workflows/nuget-publish-core.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Print GLOBAL_VERSION (Secrets)
      run: echo "GLOBAL_VERSION=${{ secrets.GLOBAL_VERSION }}"

    - name: Print GLOBAL_VERSION
      run: echo "${{env.GLOBAL_VERSION}}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Specify the .NET version

    - name: Restore dependencies
      run: dotnet restore Eddy.Core/Eddy.Core.csproj

    - name: Build
      run: dotnet build Eddy.Core/Eddy.Core.csproj --no-restore -c Release /p:Version=${{env.GLOBAL_VERSION}}

    - name: Set Package Version
      run: |
        VERSION_SUFFIX="beta$(date +%Y%m%d%H%M%S)"
        echo "VERSION_SUFFIX=$VERSION_SUFFIX" >> $GITHUB_ENV

    - name: Pack
      run: dotnet pack Eddy.Core/Eddy.Core.csproj --no-build -c Release -o out /p:PackageVersion=${{ env.GLOBAL_VERSION }} /p:VersionSuffix=${{ env.GLOBAL_VERSION_SUFFIX }}

    - name: Push to NuGet
      run: dotnet nuget push out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
